    version: '3.8'

    services:
      api:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "5000:8080" # внешний порт → порт в контейнере
        depends_on:
          - db
        environment:
          - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=kurs;Username=postgres;Password=123456
          - ASPNETCORE_ENVIRONMENT=Development
          - ASPNETCORE_URLS=http://+:8080

      db:
        image: postgres:15
        restart: always
        environment:
          POSTGRES_DB: kurs
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
        ports:
          - "5433:5432"
        volumes:
          - pgdata:/var/lib/postgresql/data

    volumes:
      pgdata:
